name: Append "closes #xx" to PR

on:
  push:
    branches: [ master ]

jobs:
  append_to_description:
    runs-on: ubuntu-latest
    name: Append to PR description
    steps:
      - uses: actions/checkout@v1      
      - uses: actions/close-issue
