name: Append "closes #xx" to PR

on:
  push:
    branches: /refs/heads/*

jobs:
  append_to_description:
    runs-on: ubuntu-latest
    name: Append to PR description
    steps:
      - uses: MoonriseCo/close-issue-based-on-pr-branch-action@master

